# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraLiveShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraLiveShop
  # pod 'AgoraRtcEngine_iOS', '~> 3.1.2'
end
